bac/views/accounts.py
from flask import Blueprint,redirect,render_template,url_for
from flask import request,flash
from flask_login import current_user, login_required, login_user, logout_user
from datetime import datetime

from bac.plugins.email import send_email
from bac.plugins.models import User,db,bcrypt

from bac.utils.decorators import logout_required
from bac.utils.token import generate_token, confirm_token
from bac.utils.forms import RegisterForm, LoginForm

bp = Blueprint('accounts',__name__,url_prefix='/accounts')

@bp.before_app_request
def update_last_connection():
    if current_user.is_authenticated:
        User.query.filter_by(id=current_user.id).update(
            {'last_connection': datetime.now()}
        )

@bp.route("/register", methods=("GET", "POST"))
@logout_required
def register():
    form = RegisterForm(request.form)
    if form.validate_on_submit():

        delete_user(email=form.email.data)
        # user = User.query.filter_by(email=form.email.data).first()
        # if user is not None:
        #     login_user(user)
        #     return redirect(url_for("accounts.resend_confirmation"))
        
        user = User(firstname=form.firstname.data,
                    name=form.name.data,
                    email=form.email.data, 
                    password=form.password.data,
                    job = form.job.data,
                    is_confirmed= False,
                    confirmed_on= datetime.now())
        
        db.session.add(user)
        db.session.commit()    
        token = generate_token(user.email)
        confirm_url = url_for("accounts.confirm_email", token=token, _external=True)
        html = render_template("accounts/confirm_email.html", confirm_url=confirm_url)
        subject = "Please confirm your email"
        send_email(user.email, subject, html)
        login_user(user)

        flash("A confirmation email has been sent via email.", "success")
        return redirect(url_for("accounts.inactive"))

    return render_template("accounts/register.html", form=form)

@bp.route("/login", methods=("POST",))
@logout_required
def login():
    form = LoginForm(request.form)

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, request.form["password"]):
            print(f'Log in {user.firstname}')
            login_user(user,remember = form.remember)            
        else:
            print("Invalid email and/or password.", "danger")
    else:
        print('Form not validate')
    return redirect(url_for('index'))

@bp.route("/logout")
@login_required
def logout():
    logout_user()
    print("You were logged out.", "success")
    return redirect(url_for("index"))

@bp.route("/confirm/<token>")
@login_required
def confirm_email(token):
    if current_user.is_confirmed:
        print("Account already confirmed.", "success")
        return redirect(url_for("index"))
    email = confirm_token(token)
    user = User.query.filter_by(email=current_user.email).first_or_404()
    if user.email == email:
        user.is_confirmed = True
        user.confirmed_on = datetime.now()
        db.session.add(user)
        db.session.commit()
        print("You have confirmed your account. Thanks!", "success")
    else:
        print("The confirmation link is invalid or has expired.", "danger")
    return redirect(url_for("index"))

@bp.route("/inactive")
@login_required
def inactive():
    if current_user.is_confirmed:
        return redirect(url_for("index"))
    return render_template("accounts/inactive.html")

@bp.route("/resend")
@login_required
def resend_confirmation():
    if current_user.is_confirmed:
        print("Your account has already been confirmed.", "success")
        return redirect(url_for("index"))
    token = generate_token(current_user.email)
    confirm_url = url_for("accounts.confirm_email", token=token, _external=True)
    html = render_template("accounts/confirm_email.html", confirm_url=confirm_url)
    subject = "Please confirm your email"
    send_email(current_user.email, subject, html)
    print("A new confirmation email has been sent.", "success")
    return redirect(url_for("accounts.inactive"))

def delete_user(email):
    User.query.filter_by(email=email).delete()

bac/views/session.py
from flask import Blueprint,render_template,request,session
from flask import redirect, url_for,jsonify
from flask_login import login_required
from sqlalchemy.sql.expression import func
import random
import json

from bac.plugins.models import Question, Answer,Image, db
from bac.utils.forms import SettingsForm

bp = Blueprint('session',__name__)

@bp.route('/',methods=('GET','POST'))
def index():
    if request.method == 'POST':
        return redirect(url_for('accounts.login'),code=307)
    
    settings = {
        'title':'Bac++',
        'subtitle': 'Bactériologie médicale',  
        'body':'Test tes connaissances en bactériologie médicale',
        'photo':"static/images/home.png"
    }

    return render_template('session/index.html', **settings)

@bp.route('/start',methods=('GET',))
def start():
    training = True #TODO should be in the user's profile
    questions = get_questions() 

    if len(questions) == 0:
        return redirect(url_for('session.index'))
    session['score'] = 0
    session['solutions'] = [q['solution'] for q in questions]

    if not training:
        for question in questions:
            del question['solution']    
    print(f'Questions {questions}')
    return render_template('session/question.html',questions=questions)

@bp.route('/answer',methods=('GET','POST',))
def answer():
    solutions = session.get('solutions',[])
    score = session.get('score',0)
    if request.method == 'POST':
        error = None
        score = request.form.get('score','0')
        try:
            score = int(score)
        except:
            score = 0
        answers = request.form.get('answer',[])
        answers = json.loads(answers)       
        if len(answers) == len(solutions):
            sc = 0
            for answer,solution in zip(answers,solutions):
                if check_answer(answer,solution):
                    sc += 1            
            if score > 0 and sc != score:
                print("Bad score",sc,score) 
            score = sc
        else:
            print(answers)
            print(solutions)
            error = "Wrong number of answers " 
        print('Score:', score)
        session['score'] = score
        if error is not None:
            print(error)
            return jsonify(error=error), 400
        return jsonify({'msg':'Answers submited'})
    
    total = len(solutions)
    return render_template('session/result.html',score=score,total=total)

@bp.route("/settings",methods=("POST","GET"))
@login_required
def settings():
    form = SettingsForm(request.form)
    if request.method == 'POST':
        #TODO
        return redirect(url_for('session.index'))
    
    return render_template('session/settings.html',form=form)

def check_answer(answer,solution):
    ret = True
    for item in answer:
        if not item in solution:
            ret = False
    for item in solution:
        if not item in answer:
            ret = False
    return ret

def model2dict(model):
    result = {}
    for col in model.__table__.columns:
        value = getattr(model,col.name)
        if value is None:
            value = ''
        result[col.name] = value
    return result

def get_questions(n = 10):
    # Cette fonction devrait tenir compte du thème, erreurs passées etc
    questions = []
    models = Question.query.order_by(func.random()).limit(n)
    questions = [load_question(model) for model in models]
    return questions

def load_question(model):
    id = model.id
    question = model2dict(model)
    del question['created_on']
    
    answer = Answer.query.filter_by(question_id=id).all()
    answer = [model2dict(item) for item in answer] 
    
    size = len(answer)
    random.shuffle(answer)
    solution = [ind for ind in range(size) if answer[ind]['solution']]
    for item in answer:
        del item['solution']

    question['choice'] = answer
    question['solution'] = solution
    question['multi'] = 1 if len(solution) > 1  else 0

    image = Image.query.filter_by(question_id = id).all()
    question['image'] =  [model2dict(img) for img in image]
    return question

bac/templates/session/index.html
{% extends 'base.html' %}
{% block content%}
<div>
    <header >
        <nav class="navbar d-flex flex-wrap justify-content-between px-4 py-2 navbar-dark bg-dark">
            <a href="#" class="text-decoration-none">
                <img src="{{url_for('static',filename='images/logo.svg')}}" alg="logo" width="40" height="40" class="d-inline-block align-text-top">
            </a>
            {% if current_user.is_confirmed  %}
                <div class="col text-end">
                    {% if current_user.is_admin == 1 %}
                        <a class="btn btn-outline-primary me-2" href="{{ url_for('admin.viewquest') }}"> 
                            Questions 
                        </a>
                    {% endif %}
                    <a class="btn btn-outline-secondary me-2" href="{{ url_for('accounts.logout') }}">
                         Déconnexion
                    </a>
                    <a class="me-3 text-secondary text-decoration-none" href="{{ url_for('session.settings') }}"> 
                        Hello {{ current_user.firstname }}!
                    </a>
                </div>
            {% else %}
                <a href="#" class="text-decoration-none text-end" data-bs-toggle="modal" data-bs-target="#login">
                    <svg class="bi d-block mx-auto mb-1" width="36" height="36"><use xlink:href="#people-circle"/></svg>
                </a>
            {% endif %}
        </nav>
    </header>
    <main>
        <div class="container col-xl-10 px-4 mt-5">
            <div class="row align-items-center g-0">
                <div class="col-lg-7 mb-4 ms-lg-4">
                    <img src="{{ photo }}" class="d-block mx-auto img-fluid rounded-3 shadow-lg" alt="" width="500" height="500" loading="lazy">
                </div>
                <div class="col-lg-5 col-md-10 mx-md-auto ms-lg-n5">
                    <div class="card shadow-lg">
                    <div class="card-body">
                        <h3 class="card-title">
                            {{ title }}
                        </h3>
                        <h4 class="card-subtitle text-muted">{{ subtitle }}</h4>
                        <p class="card-text">{{ body }}</p>
                        <a class="btn btn-primary" href="{{ url_for('session.start')}}" >Commencer</a>
                    </div>
                    </div>  
                </div>
            </div>
        </div>
        <div class="modal fade" id="login" tabindex="-1" aria-labelledby="modalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <form class="needs-validation" method="post">
                        <div class ="modal-header">
                            <h5 class="modal-title" id="modalLabel"> Connexion </h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <div class="form-floating mb-3">                                
                                <input type="text" name="email" class="form-control" id="email" placeholder="Email" required>  
                                <label for="email"> Email </label>  
                                <div class="invalid-feedback">
                                    Empty user name    
                                </div>
                            </div>
                            <div class="form-floating mb-3">                                
                                <input type="password" name="password" class="form-control" id="password" placeholder="Enter Password" required>
                                <label for="password"> Mot de passe </label>
                                <div class="invalid-feedback">
                                    Empty password
                                </div>
        
                            </div>
                            <div class="mb-3">
                                <input class="form-check-input" type="checkbox" value="" id="remember">
                                <label class="form-check-label" for="remember"> Se souvenir de moi </label>
                                <a href="#" class="float-end"> Mot de passe oublié </a>
                            </div>
                        </div>                        
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                            <button type="submit" class="btn btn-primary">Se connecter</button>
                        </div>
                        <p class="text-center"> Pas de comptes? <a href="{{ url_for('accounts.register')}}">S'inscrire</a></p>
                    </form>
                </div>
            </div>
        </div>        
    </main>
{% endblock %}

bac/templates/session/question.html
{% extends 'base.html' %}
{% block head %}
<!-- <script src="{{url_for('static',filename ='js/alpine.min.js')}}" defer="defer"></script> --->
<script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js"></script>
{% endblock %}
{% block content%}
<main>
<div class="container col-xxl-10 px-4 py-5">
    <form method="post" class="form" x-data="Form()" x-init="initForm({{ questions }})" @submit.prevent="submit">
    <div class="col g-5 py-5">
        <div class="progress">
            <div class="progress-bar" role="progressbar" :style="`width:${currentPc}%`" :aria-valuenow="currentPc" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
        <template x-if="currentQuestion.images.length === 1">
            <div class="col-lg-6">
                <img :src="currentQuestion.images[0].path" class="d-block mx-lg-auto img-fluid rounded-3 shadow-lg" alt="" width="700" height="500" loading="lazy"/>
            </div>
        </template>
        <template x-if="currentQuestion.images.length > 1">
            <div class="col-lg-6">
                <div id="carousel" class="carousel slide">
                    <div class="carousel-indicators"> 
                        <template x-for="index in currentQuestion.images.length">
                            <button type="button" data-bs-target="#carousel" :data-bs-slide-to="index-1" :aria-label="`Slide ${index}`" :class="index === 1 && 'active'" :aria-current="index === 1 && 'true'"></button>
                        </template>
                    </div>
                    <div class="carousel-inner">
                        <template x-for="(image,index) in currentQuestion.images">
                        <div class="carousel-item" :class="index === 0 && 'active'">
                            <img :src="image.path" class="d-block mx-lg-auto img-fluid rounded-3 shadow-lg" alt="" width="700" height="500" loading="lazy">
                        </div>
                        </template>
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carousel" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carousel" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>                

            </div>
        </template>

        <div class="col-lg-6">
            <h1 class="display-6 fw-bold text-body-emphasis lh-1 mb-3" x-text="currentQuestion.title"></h1>
            <p class="lead" x-text="currentQuestion.body"></p>    
            <div class="list-group list-group-style d-grid gap-2 border-0">
                <template x-for="(answer,index) in currentQuestion.choices" :key="index">
                    <div class="position-relative">
                        <input class="form-check-input position-absolute top-50 end-0 me-3 fs-5" :value="index" :type="multiAnswers() ?'checkbox':'radio'" name="listRadio" :id="`Answer${index}`" :disabled="answered">
                        <label class="py-3 pe-5 list-group-item" :class="radioStyle(index)" :for="`Answer${index}`">
                            <strong class="fw-semibold" x-text="answer.title"></strong>
                        </label>
                    </div>                        
                </template>
            </div>
        </div>
    </div>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <button type="submit" class="btn btn-primary px-4 me-md-2">Valider</button>
    </div> 
</form>   
</div>
</main>
{% endblock %}
{% block script %}
<script>
    function Form(){
        return {
            questions:[],
            currentQuestionIndex: 0,
            score: 0,
            answered: false,
            userAnswer: null,
            answers: [],

            initForm(questions){
                this.currentQuestionIndex = 0;
                this.score = 0;                
                this.answered = false;
                this.userAnswer = null;
                this.answers = [];
                this.loadQuestions(questions)
            },
            loadQuestions(input){
                this.questions = []
                for(item of input) {
                    newQuestion = {
                        title: item.title,
                        body: item.body || '',
                        legend: item.legend || '',
                        multi: item.multi > 0,
                        images: item.image,
                        choices: item.choice,
                        correctAnswer: item.solution || [],
                    };
                    this.questions.push(newQuestion)
                }
            },
            get currentQuestion(){
                return this.questions[this.currentQuestionIndex];
            },
            get currentPc(){
                return this.currentQuestionIndex < this.questions.length ?
                 (100 * this.currentQuestionIndex)/this.questions.length : 100;
            },
            solutionAvailable(){
                ret = true;
                for(q of this.questions) {
                    ret &= q.correctAnswer.length > 0;
                }
                return ret;
            },
            currentSolutionAvailable(){
                return this.currentQuestionIndex < this.questions.length &&
                    this.currentQuestion.correctAnswer.length > 0;
            },
            testFinished(){
                return this.currentQuestionIndex + 1 >= this.questions.length;
            },
            multiAnswers(){
                return this.currentQuestion.multi || 
                    this.currentQuestion.correctAnswer.length > 1;
            },
            radioStyle(index) {
                if(!this.answered) {
                    return ""
                }
                if(this.checkIndex(index)) {
                    return "list-success-item"
                }
                return ""
            },
            checkIndex(index){
                return this.currentQuestion.correctAnswer.includes(index)
            },
            checkAnswer(){
                let check = true;
                this.userAnswer.forEach(element => {
                    if(!this.currentQuestion.correctAnswer.includes(element))
                        check = false;
                });
                if(check){
                    this.currentQuestion.correctAnswer.forEach(element => {
                        if(!this.userAnswer.includes(element))
                        check = false;
                    })
                }
                return check;
            },
            submit(){
                if (this.answered) return;
                this.answered = true;

                const length = this.currentQuestion.choices.length
                this.userAnswer = [...Array(length).keys()].filter(
                    value => document.getElementById(`Answer${value}`).checked
                );
                this.answers.push(this.userAnswer);
                if(this.currentSolutionAvailable()) {
                    if (this.checkAnswer()) {
                        this.score += 1;
                    }
                    console.log(`Score: ${this.score}`)
                    setTimeout(() => {
                        if (this.testFinished()) {
                            this.sendAnswers()
                        } else {
                            this.reset()
                        }
                    }, 500);
                } else {
                    if (this.testFinished()) {
                            this.sendAnswers()
                        } else {
                            this.reset()
                        }
                }
            },
            reset(){
                for(index = 0; index < this.currentQuestion.choices.length;++index) {
                            document.getElementById(`Answer${index}`).checked = false;
                        }
                        this.currentQuestionIndex += 1;
                        this.answered = false;
                        this.userAnswer = null;
            },
            sendAnswers(){
                let formData = new FormData();
                if(this.solutionAvailable()){
                    formData.append('score',this.score);
                }
                formData.append('answer',JSON.stringify(this.answers));
                this.send(formData);
            },
            async send(formData){
                fetch(`answer`, {
                        method: 'POST',
                        body: formData,
                        })
                try {
                    const response = await fetch(`answer`, {
                        method: 'POST',
                        body: formData,
                        })
                    if (response.ok) {                        
                        console.log("Submission succeeded")
                    } else {
                        console.error('Submission failed', response)
                    }
                } catch (error) {
                    console.error('Error submitting answer', error)
                }
                window.location.href = "answer"                                
            },
        };
    }    
</script>
{% endblock %}

bac/templates/session/result.html
{% extends 'base.html' %}
{% block content%}
<body>
  <div class="card shadow-lg d-flex aligns-items-center justify-content-center text-center w-50 position-absolute top-50 start-50 translate-middle">
      <div class="card-body">
          <h3 class="card-title">
              Test terminé
          </h3>
          <h4 class="card-subtitle text-muted"></h4>
          <p class="card-text">Score final: <span> "{{score}}/{{total}}"</span> </p>
          <a href="{{ url_for('session.index')}}" class="btn btn-secondary">Accueil</a>
          <a href="{{ url_for('session.start')}}" class="btn btn-primary">Recommencer</a>
      </div>
  </div>
</body>

{% endblock%}

bac/templates/session/settings.html
{% extends 'base.html' %}
{% block content %}

<div class="container col-lg-4 px-4">
    <main class="form-signin w-100 m-auto">
    <form role="form" method="post" action="">
        {{ form.csrf_token }}
        <h1 class="h3 mb-3 fw-normal text-center">Propriétés</h1>
        
        <div class="mb-3">
            {{form.nquestions.label(class = "col-form-label")}}
            {{form.nquestions(class = "form-control",type ="number")}}
        </div>

        <div class="form-check mb-3">
            {{ form.clock.label(class = "form-check-label") }}
            {{ form.clock(class = "form-check-input") }}
        </div>

        <div class="mb-3">
            {{form.nquestions(class = "form-control",type ="number")}}
        </div>

        <div class="form-check mb-3">
            {{ form.multiple_choice.label(class = "form-check-label") }}
            {{ form.multiple_choice(class = "form-check-input") }}
        </div>

        <div class="form-check mb-3">
            {{ form.dropdown_menu.label(class = "form-check-label") }}
            {{ form.dropdown_menu(class = "form-check-input") }}
        </div>
        <div class="form-check mb-3">
            {{ form.open_question.label(class = "form-check-label") }}
            {{ form.open_question(class = "form-check-input") }}
        </div>

        <div class="form-check mb-3">
            {{ form.antibiogram.label(class = "form-check-label") }}
            {{ form.antibiogram(class = "form-check-input") }}
        </div>

        <div class="form-check mb-3">
            {{ form.direct_exam.label(class = "form-check-label") }}
            {{ form.direct_exam(class = "form-check-input") }}
        </div>

        <div class="form-check mb-3">
            {{ form.culture.label(class = "form-check-label") }}
            {{ form.culture(class = "form-check-input") }}
        </div>
        <div class="d-grid gap-4 d-md-flex justify-content-md-end">
        <a type="button" class="btn btn-secondary" href="{{ url_for('session.index')}}">Annuler</a>
        <button class="btn btn-primary" type="submit">Enregistrer</button>
        </div>
    </form>
    </main>
</div>
{% endblock %}